# Site Settings
title:               Dave Miscampbell
tagline:             General Specific
description:         "Piano playing. Whisky drinking. Programming, Book reading. Sport watching. Technical Director at StormIdeas. Sometime I have my own thoughts."
baseurl:            #"/Lagrange"
url:                #"https://lenpaul.github.io"
github:
  url:               "https://www.miscampbell.com"
author:
  name:              "Dave Miscampbell"
  email:             "david@miscampbell.com"
  twitter:           "DaveMiscampbell"
  instagram:         "DaveMiscampbell"
  github:            "DaveMiscampbell"
  facebook:          "david.miscampbell"
  linkedin:          "davemiscampbell"
paginate:            10
google_analytics:    "UA-46951813-1"


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:
  - jekyll-paginate
  - jekyll-feed
