# Site Settings
title:               Dave Miscampbell
tagline:             General Specific
description:
baseurl:            #"/Lagrange"
url:                #"https://lenpaul.github.io"
github:
  url:               "https://miscampbell.com"
author:
  name:              "Dave Miscampbell"
  email:             "david@miscampbell.com"
  twitter:           "DaveMiscampbell"
  instagram:         "leprechaun922001"
  github:            "DaveMiscampbell"
  facebook:          "david.miscampbell"
  linkedin:          "davemiscampbell"
paginate:            10
google_analytics:    "UA-46951813-1"


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
